### ISSUE TITLE
Ajouts du support linux 

### ISSUE THREAD

**Issue by PlayGlas** [johan-perso/localchat#1]
Bonjour je suis intéressé par votre projet malheureusement je suis sur linux je ne peux donc pas utiliser votre application et j'aimerais éviter d'utiliser wine ou proton.
Je suis actuellement sur Endeavor Os (une base [arch linux](https://archlinux.org)).
Je vous propose également mon service pour l'inclure dans [le AUR d'arch linux](https://aur.archlinux.org) afin de toucher une plus grande communauté.

Bonne journée

**Comment by johan-perso** [comment]
Le projet est fonctionnel sur Linux (j'ai pu tester sur une VM Manjaro en envoyant des messages depuis/vers mon host macOS). L'interface n'est cependant pas aussi correcte que sur Windows et macOS, mais cela vient en partie d'ElectronJS.

Pour exécuter LocalChat sur Linux, vous pouvez exécuter ces commandes :

```bash
git clone https://github.com/johan-perso/localchat.git
cd localchat
npm install
npm run start
```

Il est possible de compiler l'application en fichiers exécutables via le CLI [`electron-packager`](https://github.com/electron/packager) :

```bash
electron-packager . --platform=linux --arch=x64 --icon=src/icons/icon.ico --out=release-builds --overwrite`
```

Ce n'est pas encore dans les plans de délivrer des builds pour Linux sur ce projet, mais libre à vous de le faire vous-même si vous le souhaitez !
